name: Test workflow

on:
  pull_request:
    branches: [main]
    types: [opened]
    paths:
      - 'scripts/sql/**'

jobs:
  Job1:
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
    steps:
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: print-diff
        shell: bash
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff
          echo "mydiff = "
          cat mydiff
